name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  # Job 1: Testing
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:6.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd mongo
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci

    - name: Run Tests
      run: npm test
      env:
        MONGO_URI: mongodb://localhost:27017/test_db
        JWT_SECRET: test_secret

  # Job 2: Deploy (Τρέχει ΜΟΝΟ αν πετύχει το test)
  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # Deploy μόνο όταν γίνεται push στο main
    
    steps:
      - name: Deploy to Render
        # Εδώ θα χρησιμοποιήσουμε ένα απλό curl request στο Deploy Hook του Render
        # Θα πρέπει να ορίσεις το RENDER_DEPLOY_HOOK στα GitHub Secrets αργότερα
        if: success()
        run: curl "${{ secrets.RENDER_DEPLOY_HOOK }}"